---
sidebar: sidebar 
permalink: custom-architectures-inventory-configure-block-nodes.html 
keywords: BeeGFS on NetApp, NetApp Custom Architectures, EF600 
summary: ホスト変数（host_vars）を使用して個 々 のブロックノードの設定を指定します。 
---
= 個 々 のブロックノードを設定します
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ホスト変数（host_vars）を使用して個 々 のブロックノードの設定を指定します。



== 概要

このセクションでは、の入力手順について説明します `host_vars/<BLOCK_NODE_HOSTNAME>.yml` クラスタ内のブロックノードごとにファイルを作成します。これらのファイルに含まれるのは、特定のブロックノードに固有の設定のみである必要があります。これには、次のような一般

* システム名（System Managerに表示）。
* いずれかのコントローラのHTTPS URL（REST APIを使用したシステムの管理に使用）。
* このブロックノードへの接続に使用するストレージプロトコルファイルノード。
* IPアドレスなどのホストインターフェイスカード（HIC）ポートを設定する（必要な場合）。




== 手順

で定義されているIPアドレッシング方式を参照する link:custom-architectures-plan-file-system.html["ファイルシステムを計画"^] セクションでは、クラスタ内のブロックノードごとにファイルを作成します `host_vars/<BLOCK_NODE_HOSTNAME>/yml` 次のように入力します。

. 上部で、いずれかのコントローラのシステム名とHTTPS URLを指定します。
+
[source, yaml]
----
eseries_system_name: <SYSTEM_NAME>
eseries_system_api_url: https://<MANAGEMENT_HOSTNAME_OR_IP>:8443/devmgr/v2/
----
. を選択します link:https://github.com/netappeseries/santricity/tree/release-1.3.1/roles/nar_santricity_host#role-variables["プロトコル"^] ファイルノードはこのブロックノードへの接続に使用します。
+
.. サポートされるプロトコル： `auto`、 `iscsi`、 `fc`、 `sas`、 `ib_srp`、 `ib_iser`、 `nvme_ib`、 `nvme_fc`、 `nvme_roce`。
+
[source, yaml]
----
eseries_initiator_protocol: <PROTOCOL>
----


. 使用するプロトコルによっては、HICポートの設定を追加する必要があります。HICポートの設定は、必要に応じて各コントローラの設定の一番上のエントリが各コントローラの物理的な左端のポートに対応し、一番下のポートが最も右のポートになるように定義する必要があります。現在使用していないポートでも、すべてのポートで有効な設定が必要です。
+

IMPORTANT: EF600ブロックノードでHDR（200GB）InfiniBandまたは200GBのRoCEを使用している場合は、次のセクションも参照してください。

+
.. iSCSIの場合：
+
[source, yaml]
----
eseries_controller_iscsi_port:
  controller_a:         # Ordered list of controller A channel definition.
    - state:            # Whether the port should be enabled. Choices: enabled, disabled
      config_method:    # Port configuration method Choices: static, dhcp
      address:          # Port IPv4 address
      gateway:          # Port IPv4 gateway
      subnet_mask:      # Port IPv4 subnet_mask
      mtu:              # Port IPv4 mtu
    - (...)             # Additional ports as needed.
  controller_b:         # Ordered list of controller B channel definition.
    - (...)             # Same as controller A but for controller B

# Alternatively the following common port configuration can be defined for all ports and omitted above:
eseries_controller_iscsi_port_state: enabled         # Generally specifies whether a controller port definition should be applied Choices: enabled, disabled
eseries_controller_iscsi_port_config_method: dhcp    # General port configuration method definition for both controllers. Choices: static, dhcp
eseries_controller_iscsi_port_gateway:               # General port IPv4 gateway for both controllers.
eseries_controller_iscsi_port_subnet_mask:           # General port IPv4 subnet mask for both controllers.
eseries_controller_iscsi_port_mtu: 9000              # General port maximum transfer units (MTU) for both controllers. Any value greater than 1500 (bytes).

----
.. iSERの場合：
+
[source, yaml]
----
eseries_controller_ib_iser_port:
  controller_a:    # Ordered list of controller A channel address definition.
    -              # Port IPv4 address for channel 1
    - (...)        # So on and so forth
  controller_b:    # Ordered list of controller B channel address definition.
----
.. NVMe/IB：
+
[source, yaml]
----
eseries_controller_nvme_ib_port:
  controller_a:    # Ordered list of controller A channel address definition.
    -              # Port IPv4 address for channel 1
    - (...)        # So on and so forth
  controller_b:    # Ordered list of controller B channel address definition.
----
.. NVMe/RoCEの場合：
+
[source, yaml]
----
eseries_controller_nvme_roce_port:
  controller_a:         # Ordered list of controller A channel definition.
    - state:            # Whether the port should be enabled.
      config_method:    # Port configuration method Choices: static, dhcp
      address:          # Port IPv4 address
      subnet_mask:      # Port IPv4 subnet_mask
      gateway:          # Port IPv4 gateway
      mtu:              # Port IPv4 mtu
      speed:            # Port IPv4 speed
  controller_b:         # Ordered list of controller B channel definition.
    - (...)             # Same as controller A but for controller B

# Alternatively the following common port configuration can be defined for all ports and omitted above:
eseries_controller_nvme_roce_port_state: enabled         # Generally specifies whether a controller port definition should be applied Choices: enabled, disabled
eseries_controller_nvme_roce_port_config_method: dhcp    # General port configuration method definition for both controllers. Choices: static, dhcp
eseries_controller_nvme_roce_port_gateway:               # General port IPv4 gateway for both controllers.
eseries_controller_nvme_roce_port_subnet_mask:           # General port IPv4 subnet mask for both controllers.
eseries_controller_nvme_roce_port_mtu: 4200              # General port maximum transfer units (MTU). Any value greater than 1500 (bytes).
eseries_controller_nvme_roce_port_speed: auto            # General interface speed. Value must be a supported speed or auto for automatically negotiating the speed with the port.
----
.. FCプロトコルとSASプロトコルについては、追加の設定は必要ありません。SRPの使用は推奨されません。




iSCSI CHAPの設定など、HICポートとホストプロトコルを設定するその他のオプションについては、を参照してください link:https://github.com/netappeseries/santricity/tree/release-1.3.1/roles/nar_santricity_host#role-variables["ドキュメント"^] SANtricity コレクションに含まれています。注：BeeGFSを導入する場合は'ストレージ・プール'ボリューム構成'その他のプロビジョニング・ストレージの設定は他の場所で行いますこのファイルでは定義しないでください

をクリックします link:https://github.com/netappeseries/beegfs/blob/master/getting_started/beegfs_on_netapp/gen2/host_vars/ictad22a01.yml["こちらをご覧ください"^] たとえば、1つのブロックノードを表す完全なインベントリファイルなどです。



=== NetApp EF600ブロックノードでHDR（200GB）InfiniBandまたは200GB RoCEを使用：

EF600でHDR（200GB）InfiniBandを使用するには、物理ポートごとに2つ目の「仮想」IPを設定する必要があります。以下は、デュアルポートInfiniBand HDR HICを搭載したEF600を適切に設定する方法の例です。

[source, yaml]
----
eseries_controller_nvme_ib_port:
  controller_a:
    - 192.168.1.101 # Port 2a (physical)
    - 192.168.2.101 # Port 2a (virtual)
    - 192.168.1.100 # Port 2b (physical)
    - 192.168.2.100 # Port 2b (virtual)
  controller_b:
    - 192.168.3.101 # Port 2a (physical)
    - 192.168.4.101 # Port 2a (virtual)
    - 192.168.3.100 # Port 2b (physical)
    - 192.168.4.100 # Port 2b (virtual)
----