---
sidebar: sidebar 
permalink: custom-architectures-inventory-beegfs-metadata.html 
keywords: BeeGFS on NetApp, NetApp Custom Architectures, EF600 
summary: BeeGFSサービスは、グループ変数（group_vars）を使用して設定します。 
---
= BeeGFSメタデータサービスを定義します
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
BeeGFSサービスは、グループ変数（group_vars）を使用して設定します。



== 概要

このセクションでは、BeeGFSメタデータサービスの定義手順を説明します。このタイプのサービスは、特定のファイルシステムのHAクラスタに少なくとも1つ存在する必要があります。このサービスには、次の定義が含まれます。

* サービスのタイプ（メタデータ）。
* このBeeGFSサービスにのみ適用する設定を定義します。
* このサービスに到達できる1つ以上のフローティングIP（論理インターフェイス）の設定。
* このサービス（BeeGFSメタデータターゲット）のデータを格納する場所と方法を指定します。




== 手順

を参照しています link:custom-architectures-plan-file-system.html["ファイルシステムを計画"^] セクションで、にファイルを作成します `group_vars/meta_<ID>.yml` クラスタ内の各メタデータサービスについて、次のように設定します。

. BeeGFSメタデータサービスの設定を表すファイルを指定します。
+
[source, yaml]
----
beegfs_service: metadata
----
. このBeeGFSサービスにのみ適用する設定を定義します。でサポートされる設定パラメータは、最小で目的のTCPポートとUDPポートを指定する必要があります `beegfs-meta.conf` このほか、次のパラメータは、自動的に設定されますが、ここでは指定しないでください。 `sysMgmtdHost`、 `storeMetaDirectory`、 `connAuthFile`、 `connDisableAuthentication`、 `connInterfacesFile`および `connNetFilterFile`。
+
[source, yaml]
----
beegfs_ha_beegfs_meta_conf_resource_group_options:
  connMetaPortTCP: <TCP PORT>
  connMetaPortUDP: <UDP PORT>
  tuneBindToNumaZone: <NUMA ZONE> # Recommended if using file nodes with multiple CPU sockets.
----
. 他のサービスやクライアントがこのサービスへの接続に使用する1つまたは複数のフローティングIPを設定します（これにより、自動的にBeeGFSが設定されます） `connInterfacesFile` オプション）：
+
[source, yaml]
----
floating_ips:
  - <INTERFACE>:<IP/SUBNET> # Primary interface. Ex. i1b:100.127.101.1/16
  - <INTERFACE>:<IP/SUBNET> # Secondary interface(s) as needed.
----
. 必要に応じて、発信通信に使用できるIPサブネットを1つ以上指定します（これにより、BeeGFSが自動的に設定されます） `connNetFilterFile` オプション）：
+
[source, yaml]
----
filter_ip_ranges:
  - <SUBNET>/<MASK> # Ex. 192.168.10.0/24
----
. 次のガイドラインに従って、このサービスがデータを格納するBeeGFSメタデータターゲットを指定します（これにより、が自動的に設定されます） `storeMetaDirectory` オプション）：
+
.. 複数のBeeGFSサービス/ターゲットに同じストレージプール名またはボリュームグループ名を使用できます。必ず同じ名前を使用してください `name`、 `raid_level`、 `criteria_*`および `common_*` それぞれの構成（サービスごとに表示されるボリュームは異なるはずです）。
.. ボリュームサイズは、ストレージプール/ボリュームグループの割合として指定します。また、特定のストレージプール/ボリュームグループを使用するすべてのサービス/ボリュームで、合計サイズが100を超えないようにします。メモSSDを使用する場合は、SSDのパフォーマンスと寿命を最大限にするために、ボリュームグループには空きスペースを残しておくことを推奨します（をクリック） link:beegfs-deploy-recommended-volume-percentages.html["こちらをご覧ください"^] 詳細については、を参照してください）。
.. をクリックします link:https://github.com/netappeseries/santricity/tree/release-1.3.1/roles/nar_santricity_host#role-variables["こちらをご覧ください"^] で使用可能なすべての設定オプションのリストを表示するには、を参照してください `eseries_storage_pool_configuration`。などのオプションに注意してください `state`、 `host`、 `host_type`、 `workload_name`および `workload_metadata` ボリューム名は自動的に生成されるため、ここでは指定しないでください。




[source, yaml]
----
beegfs_targets:
  <BLOCK_NODE>: # The name of the block node as found in the Ansible inventory. Ex: netapp_01
    eseries_storage_pool_configuration:
      - name: <NAME> # Ex: beegfs_m1_m2_m5_m6
        raid_level: <LEVEL> # One of: raid1, raid5, raid6, raidDiskPool
        criteria_drive_count: <DRIVE COUNT> # Ex. 4
        common_volume_configuration:
          segment_size_kb: <SEGMENT SIZE> # Ex. 128
        volumes:
          - size: <PERCENT> # Percent of the pool or volume group to allocate to this volume. Ex. 1
            owning_controller: <CONTROLLER> # One of: A, B
----
をクリックします link:https://github.com/netappeseries/beegfs/blob/master/getting_started/beegfs_on_netapp/gen2/group_vars/meta_01.yml["こちらをご覧ください"^] たとえば、BeeGFSメタデータサービスを表す完全なインベントリファイルの例を示します。
