---
sidebar: sidebar 
permalink: beegfs-deploy-setting-up-an-ansible-control-node.html 
keywords: BeeGFS on NetApp, NetApp Verified Architecture, EF600 
summary: Ansible制御ノードを設定するには、解決策 の設定に使用できるすべてのファイルノードとブロックノードの管理ポートへのネットワークアクセスがある仮想マシンまたは物理マシンを特定します。 
---
= Ansibleコントロールノードをセットアップします
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Ansible制御ノードをセットアップするには、解決策 の設定に使用できるすべてのファイルノードとブロックノードの管理ポートへのネットワークアクセスがある仮想マシンまたは物理マシンを特定する必要があります。

次の手順はUbuntu 22.04でテストされました。使用しているLinuxディストリビューションに固有の手順については、を参照してください https://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html["Ansibleのドキュメント"^]。

. Python 3.10をインストールし、正しいバージョンのがインストールされていることを確認し `pip` ます。
+
....
sudo apt install python3.10 -y
sudo apt install python3-pip
sudo apt install sshpass
....
. シンボリックリンクを作成し、またはが呼び出されるたびにPython 3.10バイナリが使用されるようにし `python3` `python` ます。
+
....
sudo ln -sf /usr/bin/python3.10 /usr/bin/python3
sudo ln -sf /usr/bin/python3 /usr/bin/python
....
. NetApp BeeGFSコレクションに必要なPythonパッケージをインストールします。
+
....
python3 -m pip install ansible cryptography netaddr
....
+

NOTE: サポートされているバージョンのAnsibleと必要なすべてのPythonパッケージをインストールするには、BeeGFSコレクションのReadmeファイルを参照してください。サポートされているバージョンについても、で説明します link:beegfs-technology-requirements.html["技術要件"]。

. 正しいバージョンのAnsibleとPythonがインストールされていることを確認します。
+
....
ansible --version
ansible [core 2.17.2]
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.10/dist-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.10.12 (main, Jul 29 2024, 16:56:48) [GCC 11.4.0] (/usr/bin/python3)
  jinja version = 3.1.4
  libyaml = True
....
. BeeGFSの導入を表すために使用するAnsibleインベントリをGitやBitBucketなどのソース管理システムに保存し、Gitをインストールしてこれらのシステムと対話します。
+
....
sudo apt install git -y
....
. パスワードを使用しないSSHを設定します。これは、AnsibleがAnsibleの制御ノードからリモートのBeeGFSファイルノードにアクセスできるようにする最も簡単な方法です。
+
.. 必要に応じて、Ansibleのコントロールノードで、「ssh-keygen」を使用して公開鍵のペアを生成します
.. 「ssh-copy-id <IP_or_hostname>」を使用して、各ファイルノードにパスワードなしSSHを設定します
+
ブロックノードにパスワードなしのSSHを設定しないでください。サポートされていません。



. に示すBeeGFSコレクションのバージョンをインストールするには、Ansible Galaxyを使用します link:beegfs-technology-requirements.html["技術要件"]。
+
このインストールには、NetApp SANtricity ソフトウェアやホストコレクションなどのAnsibleの依存関係も含まれます。

+
....
ansible-galaxy collection install netapp_eseries.beegfs:==3.2.0
....

