---
sidebar: sidebar 
permalink: second-gen/beegfs-design-solution-sizing-guidelines.html 
keywords: BeeGFS on NetApp, NetApp Verified Architecture, EF600 
summary: BeeGFS解決策 には、検証テストに基づくパフォーマンスと容量のサイジングに関する推奨事項が含まれます。 
---
= サイジングガイドライン
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
BeeGFS解決策 には、検証テストに基づくパフォーマンスと容量のサイジングに関する推奨事項が含まれます。

ビルディングブロックアーキテクチャの目的は、特定のBeeGFSシステムの要件を満たす複数のビルディングブロックを追加することで、サイズを簡単に決定できる解決策 を作成することです。以下のガイドラインを使用して、環境の要件を満たすために必要なBeeGFSビルディングブロックの数とタイプを見積もります。

これらの見積もりは、ケースのパフォーマンスが最も優れていることに留意してください。統合ベンチマークアプリケーションは、基盤となるファイルシステムの使用を最適化するために作成され、実際のアプリケーションでは使用されない可能性があります。



== パフォーマンスのサイジング

次の表に、推奨されるパフォーマンスサイジングを示します。

|===
| 構成プロファイル | 読み取り：1MiB | 1MiBの書き込み 


| メタデータ+ストレージ | 62GiBps | 21GiBps 


| ストレージのみ | 64GiBps | 21GiBps 
|===
メタデータ容量のサイジングの推定値は、500GBの容量でBeeGFSに約1億5、000万ファイルを格納できる「経験則」に基づいています。（詳細については、のBeeGFSのマニュアルを参照してください https://doc.beegfs.io/latest/system_design/system_requirements.html["システム要件"^]. ）

アクセス制御リストやディレクトリあたりのディレクトリ数やファイル数などの機能を使用すると、メタデータスペースの消費速度にも影響します。ストレージ容量の概算値は、使用可能なドライブ容量と、RAID 6およびXFSオーバーヘッドを考慮しています。



== メタデータおよびストレージのビルディングブロックの容量サイジング

次の表に、メタデータ用の推奨容量およびストレージのビルディングブロックを示します。

|===
| ドライブサイズ（2+2 RAID 1）のメタデータボリュームグループ | メタデータ容量（ファイル数） | ドライブサイズ（8+2 RAID 6）ストレージボリュームグループ | ストレージ容量（ファイル内容） 


| 1.92TB | 1,938,577,200 | 1.92TB | 51.77TB 


| 3.84TB | 3,880,388,400 | 3.84TB | 103.55TB 


| 7.68TB | 8、125、278,000 | 7.68TB | 216.74TB 


| 15.3TB | 17、269、854、000 | 15.3TB | 460.60TB 
|===

NOTE: メタデータとストレージビルディングブロックのサイジングを行う場合、メタデータボリュームグループとストレージボリュームグループに使用するドライブを小型化することでコストを削減できます。



== ストレージ専用のビルディングブロックの容量サイジング

次の表に、ストレージ専用のビルディングブロックの容量をルールベースの設定値で示します。

|===
| ドライブサイズ（10+2 RAID 6）のストレージボリュームグループ | ストレージ容量（ファイル内容） 


| 1.92TB | 59.89TB 


| 3.84TB | 119.80TB 


| 7.68TB | 251.89TB 


| 15.3TB | 538.55TB 
|===

NOTE: グローバルファイルロックが有効になっていないかぎり、ベース（1番目）のビルディングブロックに管理サービスを含める場合のパフォーマンスと容量のオーバーヘッドは最小限です。
