---
sidebar: sidebar 
permalink: second-gen/beegfs-deploy-setting-up-an-ansible-control-node.html 
keywords: BeeGFS on NetApp, NetApp Verified Architecture, EF600 
summary: Ansible制御ノードを設定するには、解決策 の設定に使用できるすべてのファイルノードとブロックノードの管理ポートへのネットワークアクセスがある仮想マシンまたは物理マシンを特定します。 
---
= Ansibleコントロールノードをセットアップします
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Ansible制御ノードをセットアップするには、BeeGFS on NetAppソリューション用に導入されたすべてのファイルノードとブロックノードにネットワークアクセスできる仮想マシンまたは物理マシンを指定する必要があります。

推奨されるパッケージバージョンのリストについては、を参照してlink:beegfs-technology-requirements.html#ansible-control-node-requirements["技術要件"]ください。次の手順はUbuntu 22.04でテストされました。使用しているLinuxディストリビューションに固有の手順については、を参照してください https://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html["Ansibleのドキュメント"^]。

. Ansibleコントロールノードから、次のPythonおよびPython仮想環境パッケージをインストールします。
+
[source, console]
----
sudo apt-get install python3 python3-pip python3-setuptools python3.10-venv
----
. Python仮想環境の作成
+
[source, console]
----
python3 -m venv ~/pyenv
----
. 仮想環境をアクティブ化します。
+
[source, console]
----
source ~/pyenv/bin/activate
----
. アクティブ化された仮想環境内に必要なPythonパッケージをインストールします。
+
[source, console]
----
pip install ansible netaddr cryptography passlib
----
. Ansible Galaxyを使用してBeeGFSコレクションをインストールします。
+
[source, console]
----
ansible-galaxy collection install netapp_eseries.beegfs
----
. インストールされているAnsible、Python、BeeGFSコレクションのバージョンがに一致することを確認しますlink:beegfs-technology-requirements.html#ansible-control-node-requirements["技術要件"]。
+
[source, console]
----
ansible --version
ansible-galaxy collection list netapp_eseries.beegfs
----
. パスワードレスSSHを設定して、AnsibleがAnsibleコントロールノードからリモートBeeGFSファイルノードにアクセスできるようにします。
+
.. Ansibleコントロールノードで、必要に応じて公開鍵のペアを生成します。
+
[source, console]
----
ssh-keygen
----
.. 各ファイルノードへのパスワードレスSSHを設定します。
+
[source, console]
----
ssh-copy-id <ip_or_hostname>
----





IMPORTANT: ブロックノードにパスワードなしのSSHを設定しないでください。サポートされていません。
