---
sidebar: sidebar 
permalink: beegfs-gens.html 
keywords: BeeGFS on NetApp, NetApp Verified Architecture, EF600 
summary: NetApp解決策 のBeeGFSは、現在第2世代の設計です。 
---
= 設計世代
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp解決策 のBeeGFSは、現在第2世代の設計です。

第1世代と第2世代には、BeeGFSファイルシステムとNVMe EF600ストレージシステムを組み込んだベースアーキテクチャが含まれます。ただし、第2世代は、次のような追加の利点を最初に備えています。

* 2Uのラックスペースだけで、パフォーマンスと容量を2倍に向上
* 共有ディスクの2層ハードウェア設計に基づくハイアベイラビリティ（HA）
* NVIDIA DGX SuperPOD A100、H100、H200、およびB200システム向けに設計されたアーキテクチャ。以前はNVIDIAの専用受け入れクラスタで検証済みです。NVIDIA DGX SuperPOD with NetAppの詳細については、を参照してください link:https://docs.netapp.com/us-en/netapp-solutions/ai/ai-dgx-superpod.html["設計ガイド"]。




== 第2世代のデザイン

第2世代のBeeGFS on NetAppは、ハイパフォーマンスコンピューティング（HPC）、機械学習（ML）、ディープラーニング（DL）、その他の人工知能（AI）手法など、要件の厳しいワークロードのパフォーマンス要件を満たすように最適化されています。共有ディスクの高可用性（HA）アーキテクチャを組み込むことで、データの保持性と可用性が確保され、ダウンタイムやデータ損失を許容できない企業やその他の組織に最適です。第2世代の設計には、PCIe Gen5サーバーなどのコンポーネントと、NVIDIA®Quantum™QM9700 400Gb/s InfiniBandスイッチのサポートが含まれています。このソリューションは、NetAppによって検証されただけでなく、NVIDIA DGX™A100 SuperPODのストレージオプションとして外部からの認定にも合格しており、DGX SuperPOD H100、H200、B200システムの拡張認定も取得しています。



== 最初の世代のデザイン

第1世代のBeeGFS on NetAppは、NetApp EF600 NVMeストレージシステム、BeeGFS並列ファイルシステム、NVIDIA DGX™A100システム、NVIDIA®Mellanox®Quantum™QM8700 200Gb/s IBスイッチを使用して、機械学習（ML）と人工知能（AI）のワークロード向けに設計されました。この設計は、ストレージとコンピューティングのクラスタインターコネクトファブリックに200Gb/秒InfiniBand（IB）も備えており、ハイパフォーマンスワークロードに完全にIBベースのアーキテクチャを提供します。

第1世代の詳細については、を参照してください link:https://www.netapp.com/pdf.html?item=/media/25445-nva-1156-design.pdf["NVIDIA DGX A100 システムと BeeGFS を搭載した NetApp EF シリーズ AI"^]。
