---
sidebar: sidebar 
permalink: administer-clusters-failover-failback.html 
keywords: BeeGFS on NetApp, HA, Cluster, Administration, failover, failback, recovery 
summary: クラスタノード間でBeeGFSサービスを移動します。 
---
= フェイルオーバーサービスとフェイルバックサービス
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
クラスタノード間でBeeGFSサービスを移動します。



== 概要

BeeGFSサービスは、ノード間でフェイルオーバーして、ノードに障害が発生した場合でもクライアントが引き続きファイルシステムにアクセスできるようにすることも、計画的なメンテナンスを実行することもできます。このセクションでは、障害からのリカバリ後、またはノード間でサービスを手動で移動したあとに、クラスタを修復するさまざまな方法について説明します。



== 手順



=== フェイルオーバーとフェイルバック



==== フェイルオーバー（計画的）

通常、保守のために1つのファイルノードをオフラインにする必要がある場合は、そのノードからすべてのBeeGFSサービスを移動（または削除）する必要があります。そのためには、最初にノードをスタンバイにします。

`pcs node standby <HOSTNAME>`

使用状況を確認したら `pcs status` すべてのリソースが代替ファイルノードで再起動されました。必要に応じて、ノードをシャットダウンしたり他の変更を加えたりできます。



==== フェイルバック（計画的フェイルオーバーのあと）

BeeGFSサービスを優先ノードにリストアする準備ができたら、最初に実行します `pcs status` ノードリストで、ステータスがstandbyになっていることを確認します。ノードをリブートした場合、クラスタサービスをオンラインにするまではオフラインと表示されます。

[source, console]
----
pcs cluster start <HOSTNAME>
----
ノードがオンラインになったら、次のコマンドを使用して、ノードをスタンバイ状態から解除します。

[source, console]
----
pcs cluster node unstandby <HOSTNAME>
----
最後に、次のコマンドを使用してすべてのBeeGFSサービスを優先ノードに再配置します。

[source, console]
----
pcs resource relocate run
----


==== フェイルバック（計画外フェイルオーバー後）

ノードでハードウェアやその他の障害が発生した場合、HAクラスタが正常なノードに自動的に対応してサービスを移動し、管理者が適切に対処できるようにする必要があります。作業を進める前に、を参照してください link:administer-clusters-troubleshoot.html["トラブルシューティング"^] セクションで、フェイルオーバーの原因 を確認し、未解決の問題を解決します。ノードの電源がオンになり正常に戻ったら、フェイルバックを続行できます。

計画外（または計画的）リブート後にノードがブートした場合、クラスタサービスは自動的には開始されないため、最初にでノードをオンラインにする必要があります。

[source, console]
----
pcs cluster start <HOSTNAME>
----
次に、リソース障害をクリーンアップし、ノードのフェンシング履歴をリセットします。

[source, console]
----
pcs resource cleanup node=<HOSTNAME>
pcs stonith history cleanup <HOSTNAME>
----
で確認します `pcs status` ノードはオンラインで正常な状態です。デフォルトでは、BeeGFSサービスは、リソースを誤って正常なノードに戻すことを防ぐために、自動的にフェイルバックを行いません。準備ができたら、を指定してクラスタ内のすべてのリソースを優先ノードに戻します。

[source, console]
----
pcs resource relocate run
----


=== 個 々 のBeeGFSサービスを代替ファイルノードに移動します



==== BeeGFSサービスを新しいファイルノードに永続的に移動します

個 々 のBeeGFSサービスの優先ファイルノードを永続的に変更するには、Ansibleのインベントリを調整して優先ノードがリストされるようにしてから、Ansibleプレイブックを再実行します。

たとえば、次のサンプルファイルでは `inventory.yml` 、beegfs_01がBeeGFS管理サービスの実行に優先されるファイルノードです。

[source, yaml]
----
        mgmt:
          hosts:
            beegfs_01:
            beegfs_02:
----
この順序を逆にすると、beegfs_02で管理サービスが優先されます原因 。

[source, yaml]
----
        mgmt:
          hosts:
            beegfs_02:
            beegfs_01:
----


==== BeeGFSサービスを一時的に代替ファイルノードに移動します

通常、ノードのメンテナンス中に[フェイルオーバーとフェイルバックの手順]（フェイルオーバーとフェイルバックの手順）を使用して、すべてのサービスをそのノードから移動します。

何らかの理由で、個 々 のサービスを別のファイルノードに移動する必要がある場合は、次のコマンドを実行します。

[source, console]
----
pcs resource move <SERVICE>-monitor <HOSTNAME>
----

WARNING: 個 々 のリソースまたはリソースグループを指定しないでください。再配置するBeeGFSサービスのモニタ名を必ず指定しますたとえば、BeeGFS管理サービスをbeegfs_02に移動するには、次のコマンドを実行し `pcs resource move mgmt-monitor beegfs_02`ます。このプロセスを繰り返して、1つ以上のサービスを優先ノードから移動できます。サービスが新しいノードで再配置/開始されたことを確認します `pcs status` 。

BeeGFSサービスを優先ノードに戻すには'最初に一時的なリソースの制約を解除します（複数のサービスの場合はこの手順を繰り返します）

[source, yaml]
----
pcs resource clear <SERVICE>-monitor
----
次に、サービスを実際に優先ノードに戻す準備ができたら、次のコマンドを実行します。

[source, yaml]
----
pcs resource relocate run
----
このコマンドは、優先ノードに配置されていない一時的なリソース制約のないサービスを再配置します。
