---
sidebar: sidebar 
permalink: administer-clusters-maintenance-mode.html 
keywords: BeeGFS on NetApp, HA, Cluster, Administration, maintenance 
summary: 環境内の意図した変更にHAクラスタが誤って対応しないようにします。 
---
= クラスタをメンテナンスモードにします
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
環境内の意図した変更にHAクラスタが誤って対応しないようにします。



== 概要

クラスタをメンテナンスモードにすると、リソースの監視がすべて無効になり、ペースメーカーによるクラスタ内のリソースの移動や管理ができなくなります。アクセスを妨げる一時的な障害が発生した場合でも、すべてのリソースは元のノードで実行されたままとなります。次のような場合に推奨/有用です。

* ファイルノードとBeeGFSサービス間の接続を一時的に中断する可能性のあるネットワークメンテナンス。
* ブロックノードのアップグレード。
* ファイルノードのオペレーティングシステム、カーネル、またはその他のパッケージの更新。


通常、クラスタを手動で保守モードにする唯一の理由は、環境内の外部の変更にクラスタが対応できないようにするためです。クラスタ内の個 々 のノードで物理的な修復が必要な場合は、保守モードを使用せずに、そのノードを上記の手順 に従ってスタンバイにします。Ansibleを再実行するとクラスタが自動的に保守モードになり、アップグレードや設定の変更など、ほとんどのソフトウェアメンテナンスが容易になります。



== 手順

クラスタがメンテナンスモードかどうかを確認するには、次のコマンドを実行します。

[source, console]
----
pcs property show maintenance-mode
----
クラスタが正常に動作している場合はfalseが返されます。メンテナンスモードの実行を有効にするには、次の

[source, console]
----
pcs property set maintenance-mode=true
----
PCステータスを実行し、すべてのリソースに「（管理対象外）」と表示されていることを確認することで確認できます。クラスタの保守モードを解除するには、次のコマンドを実行します。

[source, console]
----
pcs property set maintenance-mode=false
----