---
sidebar: sidebar 
permalink: administer/clusters-expand-shrink-cluster.html 
keywords: BeeGFS on NetApp, HA, Cluster, Administration, replace 
summary: クラスタのビルディングブロックを追加または削除します。 
---
= クラスタを拡張または縮小します
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
クラスタのビルディングブロックを追加または削除します。



== 概要

ここでは、BeeGFS HAクラスタのサイズを調整するためのさまざまな考慮事項とオプションについて説明します。通常、クラスタのサイズはビルディングブロックを追加または削除することで調整されます。ビルディングブロックは通常、HAペアとして2つのファイルノードがセットアップされる構成です。必要に応じて、個 々 のファイルノード（または他のタイプのクラスタノード）を追加または削除することもできます。



== クラスタへのビルディングブロックの追加



=== 考慮事項

ビルディングブロックを追加してクラスタを拡張するプロセスは簡単です。個 々 のHAクラスタ内のクラスタノードの最小数と最大数に関する制限に注意して、既存のHAクラスタにノードを追加するか、新しいHAクラスタを作成するかを決定する必要があります。通常、各ビルディングブロックは2つのファイルノードで構成されますが、クラスタあたりの最小ノード数は3（クォーラムを確立するため）、推奨される最大ノード数は10（テスト済み）です。高度なシナリオでは、2ノードクラスタの導入時にBeeGFSサービスを実行しない「Tiebreaker」ノードを1つ追加できます。このような導入を検討される場合は、ネットアップサポートにお問い合わせください。

クラスタの拡張方法を決定する際には、これらの制限事項と、想定される将来のクラスタの拡張について留意してください。たとえば、6ノードクラスタの場合、ノードを4つ追加する必要があるときは、新しいHAクラスタを開始するだけで十分です。


TIP: 1つのBeeGFSファイルシステムを複数の独立したHAクラスタで構成できますこれにより、基盤となるHAクラスタコンポーネントの推奨される制限やハード制限をはるかに超えてファイルシステムを継続的に拡張できます。



=== 手順

クラスタにビルディングブロックを追加する場合は `host_vars`、新しいファイルノードおよびブロックノード（E-Seriesアレイ）ごとにファイルを作成する必要があります。これらのホストの名前は、作成する新しいリソースとともにインベントリに追加する必要があります。 `group_vars`新しいリソースごとに対応するファイルを作成する必要があります。link:../custom/architectures-overview.html["カスタムアーキテクチャの使用"^]詳細については、を参照してください。

正しいファイルを作成したら、コマンドを使用して自動化を再実行するだけです。

[source, console]
----
ansible-playbook -i <inventory>.yml <playbook>.yml
----


== クラスタからのビルディングブロックの削除

ビルディングブロックをリタイアさせる必要がある場合は、いくつかの考慮事項に留意する必要があります。次に例を示します。

* このビルディングブロックで実行されているBeeGFSサービスは何ですか。
* ファイルノードが撤去され、ブロックノードが新しいファイルノードに接続されるだけですか。
* ビルディングブロック全体が廃止される場合、データを新しいビルディングブロックに移動したり、クラスタ内の既存のノードに分散させたり、新しいBeeGFSファイルシステムやその他のストレージシステムに移動したりする必要がありますか。
* これはシステム停止中に発生するか、またはシステムを停止せずに実行する必要がありますか？
* ビルディングブロックがアクティブに使用されているか、またはアクティブではなくなったデータが主に含まれているか。


導入にあたっては、さまざまな出発点や希望する最終状態が考えられるため、ネットアップのサポートにご連絡ください。ネットアップでは、お客様の環境と要件に基づいて最適な戦略を特定し、導入するお手伝いをいたします。
