---
sidebar: sidebar 
permalink: administer/clusters-overview.html 
keywords: BeeGFS on NetApp, HA, Cluster, Administration 
summary: BeeGFS HAクラスタの導入後の管理方法について説明します。 
---
= 概要、主要な概念、用語
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
BeeGFS HAクラスタの導入後の管理方法について説明します。



== 概要

このセクションは、BeeGFS HAクラスタを導入したあとに管理する必要があるクラスタ管理者を対象としています。Linux HAクラスタに詳しい場合でも、このガイドをよくお読みください。クラスタの管理方法には、特にAnsibleによる再設定に関していくつかの違いがあるためです。



== 主な概念

これらの概念の一部はメインlink:../get-started/beegfs-terms.html["用語と概念"]ページで紹介されていますが、BeeGFS HAクラスタのコンテキストで再紹介すると便利です。

**クラスタノード:** PacemakerサービスとCorosyncサービスを実行しており、HAクラスタに参加しているサーバ。

**ファイルノード:** 1つ以上のBeeGFS管理'メタデータ'またはストレージサービスを実行するために使用されるクラスタノード

**ブロックノード:**ファイルノードにブロックストレージを提供するNetApp Eシリーズストレージシステム。これらのノードは独自のスタンドアロンHA機能を提供するため、BeeGFS HAクラスタには参加しません。各ノードは、ブロックレイヤで高可用性を提供する2台のストレージコントローラで構成されます。

** BeeGFSサービス** BeeGFS管理'メタデータ'ストレージ・サービス各ファイルノードは、ブロックノード上のボリュームを使用してデータを格納する1つ以上のサービスを実行します。

**ビルディングブロック：** BeeGFSファイルノード、Eシリーズブロックノード、およびBeeGFSサービスを標準で導入し、NetApp Verified Architectureに基づくBeeGFS HAクラスタ/ファイルシステムのスケールアウトを簡易化します。カスタムHAクラスタもサポートされますが、多くの場合、拡張を簡易化するビルディングブロック方式が採用されています。

** BeeGFS HA Cluster：**ブロックノードによってサポートされるBeeGFSサービスの実行に使用される拡張可能なファイルノード数。BeeGFSデータを高可用性で保存します。業界で実証済みのオープンソースコンポーネントPacemakerとCorosyncにAnsibleを使用してパッケージと導入を行いました。

**クラスタサービス**は、クラスタに参加している各ノードでPacemakerサービスおよびCorosyncサービスを実行していることを意味します。注：ノードでBeeGFSサービスを実行せずに、2つのファイルノードしか必要としない場合は「Tiebreaker」ノードとしてクラスタに参加するだけで済みます。

**クラスタリソース:**クラスタ内で実行されているBeeGFSサービスごとに、BeeGFSモニタリソースと、BeeGFSターゲットのリソース、IPアドレス（フローティングIP）、BeeGFSサービスそのものを含むリソースグループが表示されます。

** Ansible：**ソフトウェアのプロビジョニング、構成管理、アプリケーション導入のためのツールで、コードとしてのインフラストラクチャを実現します。BeeGFS HAクラスタをパッケージ化することで、ネットアップのBeeGFSの導入、再構成、更新を簡易化します。

** PC:**クラスタ内の任意のファイルノードから使用可能なコマンドラインインターフェイス。クラスタ内のノードおよびリソースの状態を照会および制御するために使用します。



== 一般的な用語

**フェールオーバー:**各BeeGFSサービスには、そのノードで障害が発生しない限り、実行される優先ファイルノードがあります。BeeGFSサービスが非優先/セカンダリファイルノードで実行されている場合は'フェイルオーバー中と呼ばれます

**フェイルバック:**優先されないファイルノードから優先ノードにBeeGFSサービスを移動する動作。

** HAペア：**同じブロックノードのセットにアクセスできる2つのファイルノードは、HAペアと呼ばれることもあります。ネットアップ全体で、相互にテイクオーバーできる2台のストレージコントローラまたはノードを指します。

**Maintenance Mode：**すべてのリソース監視を無効にし、Pacemakerによるクラスタ内のリソースの移動や管理を防止します（の項も参照link:clusters-maintenance-mode.html["メンテナンスモード"^]）。

** HAクラスタ:**クラスタ内の複数のノード間でフェイルオーバー可能なBeeGFSサービスを実行する1つ以上のファイルノードが'高可用性BeeGFSファイルシステムを作成します多くの場合、ファイルノードはHAペアに構成され、クラスタ内のBeeGFSサービスのサブセットを実行できるようになります。
