---
sidebar: sidebar 
permalink: administer/clusters-ansible-pcs.html 
keywords: BeeGFS on NetApp, HA, Cluster, Administration, pcs, Ansible 
summary: HAクラスタの管理にAnsibleとPCコマンドラインツールを使用する必要があるのはどのような場合ですか？ 
---
= AnsibleとPCSツールを使用するタイミング
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
HAクラスタの管理にAnsibleとPCコマンドラインツールを使用する必要があるのはどのような場合ですか？

外部のAnsibleコントロールノードからAnsibleを使用して、クラスタの導入と再設定のすべてのタスクを完了する必要があります。クラスタの状態の一時的な変更（ノードのスタンバイへの切り替えなど）は、通常、クラスタの1つのノード（デグレード状態でないノードやメンテナンスを予定しているノード）にログインし、PCSコマンドラインツールを使用して実行します。

リソース、制約、プロパティ、BeeGFSサービスなどのクラスタ構成を変更するには、必ずAnsibleを使用します。Ansibleのインベントリとプレイブックの最新のコピーを維持すること（変更を追跡するためのソース管理に理想的）は、クラスタの管理の一部です。設定に変更を加える必要がある場合は、インベントリを更新してAnsibleプレイブックを再実行し、BeeGFS HAロールをインポートします。

HAロールでは、クラスタをメンテナンスモードにしてから、BeeGFSまたはクラスタサービスを再起動して新しい設定を適用する前に必要な変更を行います。通常、最初の導入ではノードの完全なリブートは必要ありませんが、Ansibleの再実行は一般に「安全な」手順 とみなされます。ただし、メンテナンス時間中や、BeeGFSサービスの再起動が必要になった場合は、オフ時間帯に行うことを推奨します。このような再起動によって、通常は原因 アプリケーションエラーが発生することはありませんが、パフォーマンスが低下する可能性があります（一部のアプリケーションは他のアプリケーションよりも処理能力が高い）。

Ansibleの再実行も、クラスタ全体を最適な状態に戻したい場合に選択できます。場合によっては、PCを使用する場合よりも簡単にクラスタの状態をリカバリできる可能性があります。特に、何らかの理由でクラスタが停止した緊急時に、すべてのノードが稼働状態に戻ってからAnsibleを再実行すると、PCを使用するよりも迅速かつ確実にクラスタをリカバリできます。
