---
sidebar: sidebar 
permalink: beegfs-terms.html 
keywords: BeeGFS on NetApp, NetApp Verified Architecture, EF600 
summary: NetApp解決策 上のBeeGFSに適用される用語と概念 
---
= 用語と概念
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
以下の用語と概念は、NetApp解決策 のBeeGFSに適用されます。

[cols="25h,~"]
|===
| 期間 | 説明 


 a| 
AI
 a| 
人工知能



 a| 
Ansible のインベントリ
 a| 
目的のBeeGFS HAクラスタを記述するYAMLファイルを含むディレクトリ構造。



 a| 
BMC の場合
 a| 
ベースボード管理コントローラ：サービスプロセッサと呼ばれることもあります。



 a| 
ブロックノード
 a| 
ストレージシステム：



 a| 
クライアント
 a| 
サーバノード：



 a| 
DL
 a| 
ディープラーニング。



 a| 
ファイルノード
 a| 
BeeGFSファイルサーバ：



 a| 
高可用性
 a| 
高可用性：



 a| 
HIC
 a| 
ホストインターフェイスカード。



 a| 
HPC
 a| 
ハイパフォーマンスコンピューティング。



 a| 
HPCスタイルのワークロード
 a| 
HPCスタイルのワークロードの特徴は、通常、複数のコンピューティングノードまたはGPUがあり、すべてが同じデータセットに並行してアクセスする必要があることです。これにより、分散型のコンピューティングジョブやトレーニングジョブを円滑に進めることができます。多くの場合、このデータセットは大容量ファイルで構成されており、複数の物理ストレージノードにまたがってストライピングする必要があります。これにより、従来のハードウェアのボトルネックによって、単一ファイルへの同時アクセスが妨げられることがなくなります。



 a| 
ml
 a| 
機械学習。



 a| 
NLP
 a| 
自然言語処理。



 a| 
NLU
 a| 
自然言語の理解。



 a| 
NVA
 a| 
NetApp Verified Architecture（NVA）プログラムは、特定のワークロードとユースケースに対するリファレンス構成とサイジングに関するガイダンスを提供します。これらのソリューションは徹底的にテストされており、導入リスクを最小限に抑え、製品化サイクルを短縮するように設計されています。

|===